---
title: "zavala_anthony_critcher2013"
format: html
editor: visual
---

\
\

<https://drive.google.com/file/d/182sSzaaCkCtBFzJWphGbDNWhHVsF7vaM/view>

\

<https://github.com/ucsd-psych201a/critcher2013_2/issues>

\
\

**Critcher2013**

Introduction

\
\

I chose to replicate this project because of how it relates to my research interest

in misinformation in how people develop their beliefs in ideas from social media such as

the far right. This theory is based on the idea of how people make quick judgments based on others' quick decisions. The idea of people reacting to misinformation quickly based on assumptions is similar to this research done in this article. I am excited to hear more about how important reaction ime is going to affect people's judgments on others.

\

I would like to conduct thai by doing one question similar to the one about Pamela who gives her children a man for adoption. They have this situation and have participants react to it and start to compare in which Pamela makes the decision quickly or longer and based on her response. This project is about people making quick judgments based on others' quick decisions such as in the action of selling one’s child and many other examples. This could be in a matter of seconds in a certain group of experiments to test the reactant time and difference whether it be positive or negative based on an individual's action.

\

Methods

\

-   Power Analysis

-   Planned Sample (Don’t need now)

-   Materials

\

“Quickness. As a manipulation check, participants indicated

how quickly (vs. slowly) the decision was made”.

\

Moral character evaluation. The three moral evaluation items

had participants assess the agents’ underlying moral principles

and standards  by asking whether the agent: ‘‘has entirely good (vs. entirely bad) moral

principles,’’ ‘‘has good (vs. bad) moral standards,’’ and ‘‘deep

down has the moral principles and knowledge to do the right

thing.’’

\

Certainty. We included 4 items to assess each actor’s perceived decision certainty. Participants indicated ‘‘how conflicted \[each\] felt when making his decision’’ (reverse-scored), ‘‘how many reservations \[each\] had’’ (reverse-scored), whether the target ‘‘was quite certain in his decision’’ (vs. had considerable reservations), and ‘‘how far \[each\] was from choosing the alternate course of action.’’ The items had high internal reliability for both Justin (a 1⁄4 .89) and Nate (a 1⁄4 .81).

\

Emotional impulsivity. In order to ensure that decision speed

was not simply taken as a proxy for emotional impulsivity

(a feature previously shown to affect moral judgments; Pizarro,

Uhlmann, & Salovey, 2003), we assessed perceptions of the

emotionally impulsive nature of the decision with 2 items.

Participants indicated to what extent the person remained

‘‘calm and emotionally contained’’ (reverse-scored) and

‘‘became upset and acted without thinking.’’ The items

were significantly correlated (Justin: r 1⁄4 .51, p \< .001; Nate:

r 1⁄4 .33, p \< .001).”(Perceived Motives: "...participants rated Pamela’s motives to: “get more money” and"protect her children"."

\

-   “Participants read about Pamela, who struggled to earn enough to provide for her two children. Pamela worked for Mr. Muir, a wealthy bachelor who took a special interest in Pamela’s son Alan, taking him on outings and buying him expensive presents. Although Pamela had no direct evidence that Mr. Muir’s intentions were unsavory, his obsession with Alan made Pamela feel suspicious of Muir’s true intentions. One day, Mr. Muir approached Pamela with a proposition. He told Pamela that he cared for Alan very much and would like to adopt him. If Pamela agreed, Muir would triple her sal- ary. We assumed that people would find it morally abhorrent to, in effect, sell one’s son to a man who might abuse him. Pamela was described as taking 3 seconds (quick) or 3 days (slow) to make her decision. We independently varied whether Pamela accepted or rejected Mr. Muir’s offer to sell her son. Participants answered the same quickness, moral character eva- luation (a 1⁄4 .83), certainty (a 1⁄4 .86), and emotional impulsivity (r 1⁄4 .43) items as in Experiment 2. We added 2 items that assessed Pamela’s perceived motives. On scales from 1 (not at all) to 7 (very strong), participants rated Pamela’s motives to: ‘‘get more money’’ and ‘‘protect her children’’ (r 1⁄4 .64, p \< .001).”

    -   

-   Procedure

We got participants in groups to analyze them into four groups to analyze the situation in which a woman gives her child up for adoption based on reaction time..  The four groups were made of 2 quick and 2 slow decisions rejected and accepted. These decisions were made in 3 seconds or 3 days. We had scales from 1 to 7 to rate her motives and whether she wanted getting more money or protecting her children. 

\
\

Attention Check

\

-   Analysis Plan

We got rid of participants who they can’t find data on in the missing data section. We used a two-way ANOVA in order to find the main effect of decision type and how fast the decision is  based on the how good the person is We used a two-way ANOVA in order to analyze the interaction effects from how fast the decision is done and the type of decision We used T-tests in order to have a comparison of how decision speed on both types of decision impacted moral character evaluation.T-tests for perceived certainty of decisions and its relationship to decision speed and perceived impulsivity.  We used a 2 (decision) x 2 (speed) ANOVA was performed to analyze the perceived motives of Pamela

-   

\

-   **Differences from original study**

We are only doing experiment 2 which we will replicate in order to analyze the situation . The people who are participating in the study are not students from a university but rather from a website. This study will be conducted through the internet causing an impact in the way the people can give a response. The environment in which it is conducted will be different as well since we are having two different ways in which people answer the questions.

\

**Attention check**

At the end of the question we are adding a attention check to make sure participants we are pay attention

\

**Results**

\

-   **Data Preparation**

In order to start to get rid of missing values we need to get rid of  data with failed attention checks. This has importance because of the way the values impact the study.We need to lLook towards assessing outliers to see how much of an impact they will have and prevent any issues.. We need to make sure we have the correct data formatting in order to not get the data lost.

\
\
\
\

Results Confirmatory analysis 

The statistical test we decided on was  replicating experiment 1 which utilizes a two way ANOVA based on what the perceived morals of someone character composite confirmed through the influence of how fast the decision was T-tests . We did this in order to find a comparison of how fast the decision is on both types of decision impacting what the moral character is like T-tests.

\
\

Attention Check

At the end of the question we are adding an attention check to make sure participants are paying attention.

\
